// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoBinas.Infrastructure.Data;

#nullable disable

namespace ProyectoBinas.Migrations
{
    [DbContext(typeof(PalindromoDbContext))]
    partial class PalindromoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProyectoBinas.Core.Entities.Numero", b =>
                {
                    b.Property<int>("Numero_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("EsImpar")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EsPar")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaConsulta")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("Numero_ID");

                    b.ToTable("Numeros");
                });

            modelBuilder.Entity("ProyectoBinas.Core.Entities.Palindromo", b =>
                {
                    b.Property<int>("Palindromo_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("EsPalindromo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaConsulta")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Palabra")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Palindromo_ID");

                    b.ToTable("Palindromos");
                });
#pragma warning restore 612, 618
        }
    }
}
